language: c
script: cmake
install: libgc-dev libgc1c2
compiler:
    - clang
    - gcc
script: cmake . && make
notifications:
    email:
        recipients:
            - akoskovacs@gmx.com
        on_faulure: always
