; This program just writes an arbitrary line to an arbitrary file
(DISPLAY "Please give the filename: ")
(SET! fname (GETLINE stdin))
(IF (NIL? (SET! file (FOPEN fname "w")))
    (PROGN (DISPLAY "Cannot open " fname "!")
           (NEWLINE)
           (EXIT 1)
    )
)
(DISPLAY "Line to write: ")
(SET! line (GETLINE stdin))
(PRINT file "%s\n" line)
(FCLOSE file)
